[package]
name = "linutil_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
crossterm = "0.29.0"
ratatui = "0.29.0"
serde = "1.0.219"
tokio = { version = "1.46.0", features = ["full"] }
toml = "0.8.23"
